logo: /assets/img/logo.png
title : Hari Prasath
description: Software Engineer with 2+ years of experience specializing in Python. Passionate about building scalable, efficient, and user-friendly applications..
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
